version: '3.3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./inventario_map:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start.sh

  mysql:
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: .
      dockerfile: ./compose/local/mysql/Dockerfile
    volumes:
      - pnsu_app_data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./.env

volumes:
  pnsu_app_data: {}
