# Generated by Django 2.1.5 on 2019-02-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_patrimonio', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('fecha_garantia', models.DateTimeField(auto_now=True)),
                ('serie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Moviles',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=16)),
                ('fecha_asignacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=100)),
                ('cod_pedido', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('valor_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_adquisicion', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=200)),
                ('cod_pedido', models.IntegerField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('valor_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ruc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('denominacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('anexo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('Ordencompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.OrdenCompra')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_hardware', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_cese', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100)),
                ('anexo', models.CharField(max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Area')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Contrato')),
            ],
        ),
        migrations.AddField(
            model_name='software',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Usuario'),
        ),
        migrations.AddField(
            model_name='sedes',
            name='encargado',
            field=models.ForeignKey(on_delete=True, to='addi.Usuario'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='provedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Proveedor'),
        ),
        migrations.AddField(
            model_name='moviles',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Usuario'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.OrdenCompra'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Sedes'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='tipo_hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.TipoHardware'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Usuario'),
        ),
        migrations.AddField(
            model_name='area',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Unidad'),
        ),
    ]
