# Generated by Django 2.1.4 on 2019-01-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provedor',
        ),
    ]
