# Generated by Django 2.1.4 on 2019-01-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addi', '0002_delete_provedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ruc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
