# Generated by Django 2.1.4 on 2019-01-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addi', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenservicio',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_adquisicion', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=200)),
                ('cod_pedido', models.IntegerField()),
                ('Unidad_medida', models.CharField(max_length=50)),
                ('valor_total', models.IntegerField()),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Proveedor')),
            ],
        ),
    ]
