# Generated by Django 2.1.4 on 2019-01-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addi', '0004_ordenservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordencompra',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(max_length=100)),
                ('cod_pedido', models.IntegerField()),
                ('Unidad_medida', models.CharField(max_length=50)),
                ('valor_total', models.IntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Proveedor')),
            ],
        ),
    ]
