# Generated by Django 2.1.4 on 2019-01-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addi', '0005_ordencompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('denominacion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('anexo', models.IntegerField()),
                ('encargado', models.ForeignKey(on_delete=True, to='addi.Usuario')),
            ],
        ),
    ]
