# Generated by Django 2.1.4 on 2019-01-28 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addi', '0007_tipohardware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_patrimonio', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('fecha_garantia', models.DateTimeField(auto_now=True)),
                ('serie', models.CharField(max_length=100)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Ordencompra')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Sedes')),
                ('tipo_hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Tipohardware')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Moviles',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=16)),
                ('fecha_asignacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Usuario')),
            ],
        ),
    ]
