# Generated by Django 2.1.4 on 2019-02-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addi', '0008_hardware_moviles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('Ordencompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Ordencompra')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.Usuario')),
            ],
        ),
    ]
