# Generated by Django 2.1.5 on 2019-02-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addi', '0009_software'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='Unidad_medida',
            new_name='unidad_medida',
        ),
        migrations.RenameField(
            model_name='ordenservicio',
            old_name='Unidad_medida',
            new_name='unidad_medida',
        ),
        migrations.AlterField(
            model_name='hardware',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.OrdenCompra'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='tipo_hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.TipoHardware'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='software',
            name='Ordencompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addi.OrdenCompra'),
        ),
    ]
